version: "3.8"

services:
  db:
    image: mysql:8.0.28
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_bin
    restart: always
    environment:
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: super_secure_password
      MYSQL_ROOT_PASSWORD: root_secure_password
  zabbix-srv:
    image: zabbix/zabbix-server-mysql:alpine-5.4.9
    depends_on:
      - db
    ports:
      - 10051:10051
    environment:
      DB_SERVER_HOST: db
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: super_secure_password
  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:alpine-5.4.9
    depends_on:
      - zabbix-srv
    ports:
      - 8080:8080
      - 8443:8443
    environment:
      ZBX_SERVER_HOST: zabbix-srv
      DB_SERVER_HOST: db
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: super_secure_password
      PHP_TZ: Asia/Yekaterinburg
  zabbix-agent:
    image: zabbix/zabbix-agent2:alpine-5.4.9
    depends_on:
      - zabbix-web
    environment:
      ZBX_HOSTNAME: srv-discovery
      ZBX_SERVER_HOST: zabbix-srv

